quarkus.smallrye-openapi.auto-add-open-api-endpoint = true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/plante_db
quarkus.datasource.username=my_user
quarkus.datasource.password=my_super_password
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true


%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
