# Configuration de la base de données
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# En mode DEV et TEST, si on ne spécifie pas l'URL, Quarkus utilise Dev Services (Docker requis)
# Si vous avez une base locale, décommentez la ligne suivante :
# quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/projetplante

# Configuration Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Configuration spécifique pour les tests (utilise Dev Services par défaut)
%test.quarkus.hibernate-orm.database.generation=drop-and-create
