apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plant-api.fullname" . }}
  labels:
    {{- include "plant-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "plant-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plant-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: plant-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: QUARKUS_PROFILE
              value: "{{ .Values.app.profile }}"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "plant-api.fullname" . }}-config
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "plant-api.fullname" . }}-config
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plant-api.fullname" . }}-secret
                  key: QUARKUS_DATASOURCE_PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}