apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plant-api.fullname" . }}-secret
  labels:
    {{- include "plant-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  QUARKUS_DATASOURCE_PASSWORD: "{{ .Values.database.password }}"