    create table care_logs (
        id bigint generated by default as identity,
        date timestamp(6) not null,
        note varchar(255),
        type varchar(255) not null check ((type in ('WATERING','FERTILIZING','PRUNING','MISTING','OTHER'))),
        plant_id bigint not null,
        user_id bigint not null,
        primary key (id)
    );

    create table home_members (
        role varchar(255) not null check ((role in ('OWNER','GUEST','ADMIN'))),
        home_id bigint not null,
        user_id bigint not null,
        primary key (home_id, user_id)
    );

    create table homes (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table plants (
        id bigint generated by default as identity,
        last_watered_date date,
        name varchar(255) not null,
        species varchar(255),
        watering_frequency integer,
        room_id bigint not null,
        primary key (id)
    );

    create table rooms (
        id bigint generated by default as identity,
        name varchar(255) not null,
        home_id bigint not null,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        email varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    );

    alter table if exists users 
       drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;

    alter table if exists users 
       add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists users 
       drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;

    alter table if exists users 
       add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);

    alter table if exists care_logs 
       add constraint FK56jycl7qks7sf1vldpvivnnar 
       foreign key (plant_id) 
       references plants;

    alter table if exists care_logs 
       add constraint FKbjk4qnrjgbbr1ethtcsfgtu3x 
       foreign key (user_id) 
       references users;

    alter table if exists home_members 
       add constraint FKqallih30oy0rv976cib7j3aa8 
       foreign key (home_id) 
       references homes;

    alter table if exists home_members 
       add constraint FKkuktnlf3rqcr5hf0bas1upjgr 
       foreign key (user_id) 
       references users;

    alter table if exists plants 
       add constraint FK4rvx7nvfjd2vch7coi6uuueb6 
       foreign key (room_id) 
       references rooms;

    alter table if exists rooms 
       add constraint FKn48gj72kbwdrsuwinm2l1ot9u 
       foreign key (home_id) 
       references homes;