ALTER TABLE plants
    ADD COLUMN IF NOT EXISTS photo_url VARCHAR(1000);

ALTER TABLE plants
    ADD COLUMN IF NOT EXISTS potted_date DATE;

ALTER TABLE plants
    ADD COLUMN IF NOT EXISTS is_deceased BOOLEAN NOT NULL DEFAULT FALSE;