name: Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: docker build --pull -t ghcr.io/tounu/plant-api:latest .
      - name: Push image
        run: docker push ghcr.io/tounu/plant-api:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.CAN_SSH_PRV_KEY }}
          script: |
            cd /srv/plant/ProjetPlante
            docker compose pull
            docker compose up -d
            docker compose logs --tail=50